### ISSUE TITLE
Tag INFO_REQ_GET_FS_USAGE fehlt

### ISSUE THREAD

**Issue by ms220112** [Spontifixus/am-e3dc#2]
Hallo,

kann es sein das der Tag INFO_REQ_GET_FS_USAGE aktuell noch fehlt?

**Comment by Spontifixus** [comment]
Moin, und danke für die Rückmeldung!

In der offiziellen Dokumentation der Tags (RSCP-Tags-Official.xlsm) finde den Tag nicht. Hast du eine Doku oder Beispielanwendung wo der dokumentiert ist? Wofür ist der denn gut?

Du kannst aber als Workaround den Tag auch direkt angeben und ihn auf `RscpTag` casten. Das funktioniert auch für Werte die in der Enumeration nicht definiert sind wie hier am Beispiel des Batterieindex gezeigt:

```csharp
new RscpContainer(RscpTag.BAT_REQ_DATA)
{
    new RscpInt32((RscpTag)0x03040001, 0), // entspricht RscpTag.BAT_INDEX
    new RscpVoid(RscpTag.BAT_REQ_CHARGE_CYCLES)
}
```

**Comment by ms220112** [comment]
Hallo,

die Definition des Tags ist die INFO über das Filesystem des Wechselrichters.

INFO_REQ_GET_FS_USAGE 0x0A000025
INFO_REQ_GET_FS_USAGE 0x0A800025

Wo genau ich diese Information her habe kann ich nicht genau sagen.

Ich habe eine eigene Dokumentation erstellt, in der ich alle Tags inkl. deren Bedeutung zusammengefasst habe. Das Original von E3DC ist da ja nicht sehr aussagekräftig und auch veraltet, zu mindestens die Versionen, die ich gefunden habe.

Auch ist der Inhalt einiger Felder abhängig von z.B. der verwendeten Wallbox. Die Werte für die neue Multiconnect ( bei uns im Einsatz) stimmen nicht mit der Beschreibung überein.

Bei Bedarf kann ich meine erweiterte Dokumentation gerne zur Verfügung stellen.

Das mit dem direkt casten werde ich mal ausprobieren, wird aber wohl erst heute Abend oder Morgen möglich sein, ich gebe dann Rückmeldung-

**Comment by Spontifixus** [comment]
An deiner Doku wäre ich in der Tat interessiert!

**Comment by ms220112** [comment]
Doku anbei
[Dokumentation E3DC RSCP.xlsx](https://github.com/Spontifixus/am-e3dc/files/14587178/Dokumentation.E3DC.RSCP.xlsx)

**Comment by ms220112** [comment]
Mit dem Casten hat funktioniert, herzlichen Dank für die Info.
Dann kann ich jetzt auch einige der anderen fehlenden Tags abfragen

**Comment by Spontifixus** [comment]
Der Vollständigkeit halber: Ich habe mich entschlossen zunächst keine weiteren Tags in die Enumeration aufzunehmen, aber einen Hinweis auf die Option einen Wert auf `RscpTag` zu casten in die Dokumentation aufgenommen.
